import type { Metadata } from 'next'
import './globals.css'
import { ApolloWrapper } from '@/gql/apollo-wrapper'
import { ThemeProvider } from '@/components/core/ThemeProvider'
import { LocalizationProvider } from '@/components/core/localization-provider'
import { UserProvider } from '@/components/core/UserProvider'
import { getUser } from '@/operations/user/get-user'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await getUser()
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <LocalizationProvider>
            <UserProvider user={user}>
              <ThemeProvider>{children}</ThemeProvider>
            </UserProvider>
          </LocalizationProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
