import * as Types from '@/gql/__generated__/types';

import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetReservedMeetingsQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetReservedMeetingsQuery = { readonly __typename?: 'Query', readonly reservedMeetings: ReadonlyArray<{ readonly __typename?: 'MeetingDto', readonly id: number, readonly userNames?: ReadonlyArray<string> | null, readonly discount?: number | null, readonly priceExcepted?: number | null, readonly priceFinal?: number | null, readonly priceFull?: number | null, readonly repeatRate?: string | null, readonly createdAt?: any | null, readonly updatedAt?: any | null, readonly createdByExternalRefId?: string | null, readonly notes?: string | null, readonly schedules?: ReadonlyArray<{ readonly __typename?: 'MeetingScheduleDto', readonly id: number, readonly startDate: any, readonly endDate: any, readonly canceled: boolean, readonly locationId: number, readonly location: { readonly __typename?: 'LocationDto', readonly city: string, readonly postalCode: string, readonly id: number, readonly houseNumber: number, readonly street: string, readonly name: string } }> | null }> };


export const GetReservedMeetingsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"getReservedMeetings"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"reservedMeetings"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"userNames"}},{"kind":"Field","name":{"kind":"Name","value":"discount"}},{"kind":"Field","name":{"kind":"Name","value":"priceExcepted"}},{"kind":"Field","name":{"kind":"Name","value":"priceFinal"}},{"kind":"Field","name":{"kind":"Name","value":"priceFull"}},{"kind":"Field","name":{"kind":"Name","value":"repeatRate"}},{"kind":"Field","name":{"kind":"Name","value":"createdAt"}},{"kind":"Field","name":{"kind":"Name","value":"updatedAt"}},{"kind":"Field","name":{"kind":"Name","value":"createdByExternalRefId"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}},{"kind":"Field","name":{"kind":"Name","value":"schedules"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"startDate"}},{"kind":"Field","name":{"kind":"Name","value":"endDate"}},{"kind":"Field","name":{"kind":"Name","value":"canceled"}},{"kind":"Field","name":{"kind":"Name","value":"locationId"}},{"kind":"Field","name":{"kind":"Name","value":"location"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"city"}},{"kind":"Field","name":{"kind":"Name","value":"postalCode"}},{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"houseNumber"}},{"kind":"Field","name":{"kind":"Name","value":"street"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}}]}}]}}]} as unknown as DocumentNode<GetReservedMeetingsQuery, GetReservedMeetingsQueryVariables>;