import type { Metadata } from 'next'
import './globals.css'
import { ApolloWrapper } from '@/gql/apollo-wrapper'
import { ThemeProvider } from '@/components/core/ThemeProvider'
import { LocalizationProvider } from '@/components/core/localization-provider'
import { UserProvider } from '@/components/core/UserProvider'
import { GetUserDocument } from '@/gql/queries/get-user.generated'
import { getClient } from '@/gql/client'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const { data, error, errors, networkStatus } = await getClient().query({
    query: GetUserDocument,
  })
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <LocalizationProvider>
            <UserProvider user={data.user}>
              <ThemeProvider>{children}</ThemeProvider>
            </UserProvider>
          </LocalizationProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
