import type { Metadata } from 'next'
import './globals.css'
import { ApolloWrapper } from '@/gql/apollo-wrapper'
import { ThemeProvider } from '@/components/core/ThemeProvider'
import { LocalizationProvider } from '@/components/core/localization-provider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
          <LocalizationProvider>
            <ThemeProvider>{children}</ThemeProvider>
          </LocalizationProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
